mcp_servers:
    - name: "my_tools"
      command: "python"
      args: ["mcp_servers/my_tools_server.py"]

    - name: "filesystem"
      command: "npx"
      args: ["-y", "@modelcontextprotocol/server-filesystem", "/Users/cyan/WYH/Agent/Small_Agent"]

    - name: "markfetch"
      command: "npx"
      args: ["-y", "markfetch"]
